create table if not exists public.waitlist_signups (
  id bigint generated by default as identity primary key,
  email text not null unique,
  source text not null default 'landing_page',
  wants_testing_access boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  last_requested_at timestamptz not null default timezone('utc', now())
);

create index if not exists waitlist_signups_created_at_idx
  on public.waitlist_signups (created_at desc);
